server:
  port: 8084
spring:
  application:
    name: idstaa-service-resume
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://117.50.4.9:3306/lagou?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: idstaa
    password: Summer!idstaa
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  #避免将驼峰命名转换为下划线命名
 #Nacos 配置
  cloud:
    nacos:
      discovery:
        ################ 配置nacos server地址
        server-addr: nacos.idstaa.com:8848
        #namespace: d80e4457-1263-4482-8715-0bd7f19836e5
      config:
        server-addr: nacos.idstaa.com:8848
        #namespace: d80e4457-1263-4482-8715-0bd7f19836e5 #命名空间
        group: DEFAULT_GROUP #默认分组就是DEFAULT_GROUP
        dataid: idstaa-service-resume.yaml
        file-extension: yaml #扩展名
  #过滤掉eureka
  autoconfigure:
    exclude: org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
management:
    endpoints:
        web:
            exposure:
                include: "*"
dubbo:
    scan:
    # dubbo 服务扫描基准包
        base-packages: com.idstaa.service.impl
    protocol:
        # dubbo 协议
        name: dubbo
        # dubbo 协议端⼝（ -1 表示⾃增端⼝，从 20880 开始）
        port: -1
    registry:
    # 挂载到 Spring Cloud 的注册中⼼
        address: spring-cloud://localhost

